### ISSUE TITLE
Arbitrage

### ISSUE THREAD

**Issue by sarmel** [scalexm/trade-rs#7]
Will this crate support Arbitrage and Triangular arbitrage?

**Comment by scalexm** [comment]
@sarmel Well, I guess this will never be supported *directly* inside the crate, because this crate does not want to expose any specific trading strategy but rather provide an interface to define your own strategies, hence it won’t try to automatically detect arbitrage opportunities.

However, my dream goal would be that users wanting to design an algorithm exploiting such arbitrage opportunities would be able to easily implement their algo on top of this crate.

**Comment by sarmel** [comment]
OK. Thanks for creating and making this crate open source.
